version: '3'

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: dasha_adm
  #     POSTGRES_DB: myapp_development

  redis:
    image: redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      # - db
      - redis

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      # - db
      - redis
    environment:
      POSTGRES_USER: dasha_adm
      POSTGRES_PASSWORD: password
      RAILS_MAX_THREADS: 5